const mongoose = require('mongoose');

const StudentSchema = new mongoose.Schema({
  name: String,
  email: String,
  courseTitle: String,
  studentId: String,
  absence: String,
  late: String,
  Week1: String, 
  Week2: String,
  Week3: String,
  Week4: String,
  Week5: String,
  Week6: String,
  Week7: String,
  Week8: String,
  Week9: String,
  Week10: String,
  Week11: String,
  Week12: String,
  hw1: String,
  hw2: String,
  hw3: String,
  hw4: String,
  hw5: String,
  hw6: String,
  hw7: String,
  hw8: String,
  hw9: String,
  hw10: String,
  hw11: String,
  hw12: String,
  hw13: String,
  hw14: String,
  hw15: String,
  hw16: String,
  hw17: String,
  hw18: String,
  hw19: String,
  hw20: String,
  project1: String,
  project2: String,
  project3: String,
  project4: String,
  project5: String,
  project6: String,
  project7: String,
  project8: String,
  project9: String,
  project10: String,
}, { timestamps: true });

const Post = mongoose.model('Student', StudentSchema);

module.exports = Post;